[build]
  base = "web-dashboard"
  command = "npm ci --force && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  VITE_NODE_ENV = "production"
  VITE_ENABLE_AUTH = "false"
  VITE_BYPASS_AUTH = "true"

# SPA 라우팅을 위한 리디렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 정적 파일 캐싱 설정
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 