[build]
  command = "python setup.py"
  publish = "app/web/static"
  functions = "app/web/functions"

[dev]
  command = "python app/web/main.py"
  port = 8000
  targetPort = 8080

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/demo/*"
  to = "/.netlify/functions/demo-trade/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.10"

[functions]
  directory = "app/web/functions"
  node_bundler = "esbuild"

[functions."api/*"]
  included_files = ["app/web/**"] 