name: Beta Feedback & Issue Response Check

on:
  schedule:
    - cron: '0 */4 * * *'  # 4시간마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  check_beta_systems:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests pandas matplotlib seaborn
          
      - name: Run feedback system check
        run: python scripts/beta_feedback_system_check.py --verbose
        
      - name: Run issue response check
        run: python scripts/beta_issue_response.py --check-all
        
      - name: Generate daily report
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
        run: python scripts/beta_generate_report.py
        
      - name: Upload check results
        uses: actions/upload-artifact@v3
        with:
          name: beta-system-checks
          path: logs/beta_checks_*.log
          retention-days: 7 